name: Publish @jellyfin/ux-ios

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: ${{ github.repository == 'jellyfin/jellyfin-ux' }}
    defaults:
        run:
            working-directory: ./branding/ios
    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          check-latest: true
          cache: npm
          cache-dependency-path: ./branding/ios
          registry-url: https://registry.npmjs.org

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Publish the SDK to npm
        run: npm publish
